name: build and deploy Web & Android

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Une exécution de flux de travail est composée d'une ou plusieurs tâches appelés jobs.
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: 🏗 Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Deploy
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}